[package]
name = "BackendIntergration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
pyembed = "*"

[dependencies.pyo3]
version = "0.16.5"
features = ["auto-initialize"]